[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "out"
  functions = ".netlify/functions"

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "20.13.1"
  NPM_VERSION = "10.7.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

[build.processing]
  skip_processing = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
