import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    // Ensure these classes are never purged
    'bg-gradient-to-br',
    'from-slate-50',
    'to-blue-50',
    'dark:from-slate-900',
    'dark:to-slate-800',
    'min-h-screen',
    'container',
    'mx-auto',
    'px-4',
    'py-8',
    'text-slate-900',
    'dark:text-slate-100',
    'text-slate-600',
    'dark:text-slate-400',
    // Add more essential classes
    'bg-white',
    'dark:bg-slate-900',
    'text-center',
    'font-bold',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    'text-5xl',
    'grid',
    'grid-cols-1',
    'md:grid-cols-2',
    'lg:grid-cols-3',
    'lg:grid-cols-4',
    'gap-4',
    'gap-6',
    'gap-8',
    'p-4',
    'p-6',
    'p-8',
    'mb-4',
    'mb-6',
    'mb-8',
    'mb-12',
    'mt-4',
    'mt-6',
    'mt-8',
    'rounded-lg',
    'rounded-xl',
    'shadow-lg',
    'border',
    'border-slate-200',
    'dark:border-slate-700',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
      },
      fontFamily: {
        sans: ['var(--font-geist-sans)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-geist-mono)', 'monospace'],
      },
    },
  },
  plugins: [],
  darkMode: 'class',
}

export default config
